In [3]:
import numpy as np

In [4]:
np.random.seed(123)
aMat = np.random.randint(0, 100, (6, 10))

In [27]:
aMat

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47, 739],
       [ 73,  32,  46,  96,  25,  83, 219,  36,  96,  80, 786],
       [ 68,  49,  55,  67,   2,  84,  39,  66,  84,  47, 561],
       [ 61, 215,   7,  99,  92,  52,  97,  85,  94,  27, 829],
       [ 34,  97,  76,  40,   3,  69,  64,  75,  34,  58, 550],
       [ 10,  22,  77,  18,  15,  27,  30,  52,  70,  26, 347]])

In [28]:
#1-1
aVec = (np.mean(aMat, 0 ) >50)*1
aVec =(np.mean(aMat, 0 )> 50)*1
aVec

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1])

In [29]:
aMat[(aMat[:,4]>50 )|(aMat[:,6] <30),:]

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47, 739],
       [ 61, 215,   7,  99,  92,  52,  97,  85,  94,  27, 829]])

In [30]:
# 1-3
aMat[[3,1],[1,6]]= 999
aMat

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47, 739],
       [ 73,  32,  46,  96,  25,  83, 999,  36,  96,  80, 786],
       [ 68,  49,  55,  67,   2,  84,  39,  66,  84,  47, 561],
       [ 61, 999,   7,  99,  92,  52,  97,  85,  94,  27, 829],
       [ 34,  97,  76,  40,   3,  69,  64,  75,  34,  58, 550],
       [ 10,  22,  77,  18,  15,  27,  30,  52,  70,  26, 347]])

In [31]:
# 1-4 주의
aMat[~np.any( aMat==999, axis=1 ), :]

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47, 739],
       [ 68,  49,  55,  67,   2,  84,  39,  66,  84,  47, 561],
       [ 34,  97,  76,  40,   3,  69,  64,  75,  34,  58, 550],
       [ 10,  22,  77,  18,  15,  27,  30,  52,  70,  26, 347]])

In [32]:
np.mean(aMat[~np.any(aMat== 999, 1),:], 1)
np.std(aMat[~np.any(aMat== 999, 1),:], 1)

array([192.73451959, 146.78927382, 144.42739604,  92.24222514])

In [31]:
# 1-5 주의
aMat[aMat == 999] = np.mean(aMat, 0)[np.nonzero( aMat==999 )[1]]
aMat

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47],
       [ 73,  32,  46,  96,  25,  83, 219,  36,  96,  80],
       [ 68,  49,  55,  67,   2,  84,  39,  66,  84,  47],
       [ 61, 215,   7,  99,  92,  52,  97,  85,  94,  27],
       [ 34,  97,  76,  40,   3,  69,  64,  75,  34,  58],
       [ 10,  22,  77,  18,  15,  27,  30,  52,  70,  26]])

In [38]:
# 1-6 주의 - sum 걸면 무조건 10, 으로 바뀝니다.
aMat2 = np.vstack((aMat, np.sum(aMat, 0)))

In [52]:
aMat2 = np.hstack((aMat2, np.sum(aMat2, 1)[:,np.newaxis]))

In [53]:
aMat2

array([[  66,   92,   98,   17,   83,   57,   86,   97,   96,   47,  739],
       [  73,   32,   46,   96,   25,   83,  219,   36,   96,   80,  786],
       [  68,   49,   55,   67,    2,   84,   39,   66,   84,   47,  561],
       [  61,  215,    7,   99,   92,   52,   97,   85,   94,   27,  829],
       [  34,   97,   76,   40,    3,   69,   64,   75,   34,   58,  550],
       [  10,   22,   77,   18,   15,   27,   30,   52,   70,   26,  347],
       [ 312,  507,  359,  337,  220,  372,  535,  411,  474,  285, 3812]])

In [42]:
np.random.seed(123)
MAT = np.random.exponential(scale=1/5, size=(10, 7))
MAT= np.around(MAT, decimals=3 )

In [59]:
# 2-1
Q1 = np.percentile(MAT, 25)
Q3 = np.percentile(MAT, 75)
n1 = Q1-1.5*(Q3-Q1)
n2 = Q3+1.5*(Q3-Q1)
MAT[(MAT<n1)|(MAT>n2)]

array([0.79 , 0.577, 0.848])

In [49]:
q1 = np.percentile(MAT, 25)
q3 = np.percentile(MAT, 75)
n1 = q1 - 3/2*(q3-q1)
n2 = q3 + 3/2*(q3-q1)
MAT[(MAT>n2)|(MAT<n1)]

array([0.79 , 0.577, 0.848])

In [52]:
# 2-2
np.nonzero(np.abs(MAT-np.mean(MAT)) == np.min(np.abs(MAT-np.mean(MAT))))

(array([7], dtype=int64), array([3], dtype=int64))

In [118]:
#2-3
MAT[np.argsort(MAT[:,1]),:]

array([[0.19 , 0.026, 0.35 , 0.185, 0.158, 0.084, 0.073],
       [0.238, 0.067, 0.051, 0.16 , 0.254, 0.11 , 0.79 ],
       [0.076, 0.107, 0.402, 0.058, 0.132, 0.848, 0.147],
       [0.075, 0.111, 0.448, 0.577, 0.139, 0.196, 0.025],
       [0.231, 0.131, 0.1  , 0.084, 0.261, 0.115, 0.012],
       [0.07 , 0.199, 0.019, 0.114, 0.113, 0.136, 0.111],
       [0.108, 0.229, 0.417, 0.143, 0.221, 0.176, 0.196],
       [0.379, 0.258, 0.189, 0.256, 0.078, 0.09 , 0.052],
       [0.102, 0.268, 0.04 , 0.039, 0.152, 0.152, 0.201],
       [0.225, 0.369, 0.017, 0.289, 0.056, 0.043, 0.17 ]])

In [56]:
#2-4
MAT[:,np.argsort(np.mean(MAT,0))]

array([[0.254, 0.238, 0.067, 0.79 , 0.16 , 0.11 , 0.051],
       [0.261, 0.231, 0.131, 0.012, 0.084, 0.115, 0.1  ],
       [0.152, 0.102, 0.268, 0.201, 0.039, 0.152, 0.04 ],
       [0.078, 0.379, 0.258, 0.052, 0.256, 0.09 , 0.189],
       [0.113, 0.07 , 0.199, 0.111, 0.114, 0.136, 0.019],
       [0.139, 0.075, 0.111, 0.025, 0.577, 0.196, 0.448],
       [0.132, 0.076, 0.107, 0.147, 0.058, 0.848, 0.402],
       [0.158, 0.19 , 0.026, 0.073, 0.185, 0.084, 0.35 ],
       [0.221, 0.108, 0.229, 0.196, 0.143, 0.176, 0.417],
       [0.056, 0.225, 0.369, 0.17 , 0.289, 0.043, 0.017]])

In [67]:
#2-5 주의
MAT[[[0],[1]],[1,3,4]].reshape(6,)

array([0.067, 0.16 , 0.254, 0.131, 0.084, 0.261])

In [68]:
MAT[(MAT<n1)|(MAT>n2)] = np.nan

In [73]:
#주의
MAT[np.any(np.isnan(MAT), 1)]

array([[0.238, 0.067, 0.051, 0.16 , 0.254, 0.11 ,   nan],
       [0.075, 0.111, 0.448,   nan, 0.139, 0.196, 0.025],
       [0.076, 0.107, 0.402, 0.058, 0.132,   nan, 0.147]])