# Assignment 6

In [3]:
import numpy as np

In [18]:
# Q1
np.random.seed(123)
aMat = np.random.randint(0, 100, (6, 10))
aMat

array([[66, 92, 98, 17, 83, 57, 86, 97, 96, 47],
       [73, 32, 46, 96, 25, 83, 78, 36, 96, 80],
       [68, 49, 55, 67,  2, 84, 39, 66, 84, 47],
       [61, 48,  7, 99, 92, 52, 97, 85, 94, 27],
       [34, 97, 76, 40,  3, 69, 64, 75, 34, 58],
       [10, 22, 77, 18, 15, 27, 30, 52, 70, 26]])

In [20]:
# 1-1
aVec = np.where(np.average(aMat, 0)>50, 1,0)
aVec

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0])

In [36]:
# 1-2
aMat[(aMat[:,4]>50) | (aMat[:,6]<30),:]

array([[66, 92, 98, 17, 83, 57, 86, 97, 96, 47],
       [61, 48,  7, 99, 92, 52, 97, 85, 94, 27]])

In [223]:
# 1-3
aMat[[3,1],[1,6]] = 999
aMat

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47],
       [ 73,  32,  46,  96,  25,  83, 999,  36,  96,  80],
       [ 68,  49,  55,  67,   2,  84,  39,  66,  84,  47],
       [ 61, 999,   7,  99,  92,  52,  97,  85,  94,  27],
       [ 34,  97,  76,  40,   3,  69,  64,  75,  34,  58],
       [ 10,  22,  77,  18,  15,  27,  30,  52,  70,  26]])

In [224]:
# 1-4 How do I remove rows with 999 automatically? Is this right?
np.std(aMat[np.all(aMat!=999, 1)], 1)

array([25.43403232, 22.9540846 , 25.88822126, 22.2038285 ])

In [225]:
# 1-5
col_999 = aMat[:,np.any(aMat==999,0)]
aMat[aMat==999] = np.mean(col_999, 0)
aMat

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47],
       [ 73,  32,  46,  96,  25,  83, 215,  36,  96,  80],
       [ 68,  49,  55,  67,   2,  84,  39,  66,  84,  47],
       [ 61, 219,   7,  99,  92,  52,  97,  85,  94,  27],
       [ 34,  97,  76,  40,   3,  69,  64,  75,  34,  58],
       [ 10,  22,  77,  18,  15,  27,  30,  52,  70,  26]])

In [226]:
# 1-6 
col_sum = np.sum(aMat, 0)
aMat2 = np.vstack([aMat,col_sum])
aMat2

array([[ 66,  92,  98,  17,  83,  57,  86,  97,  96,  47],
       [ 73,  32,  46,  96,  25,  83, 215,  36,  96,  80],
       [ 68,  49,  55,  67,   2,  84,  39,  66,  84,  47],
       [ 61, 219,   7,  99,  92,  52,  97,  85,  94,  27],
       [ 34,  97,  76,  40,   3,  69,  64,  75,  34,  58],
       [ 10,  22,  77,  18,  15,  27,  30,  52,  70,  26],
       [312, 511, 359, 337, 220, 372, 531, 411, 474, 285]])

In [227]:
# Tip [:, np.newaxis] => n, 1
row_sum = np.sum(aMat2, 1)
aMat2 = np.hstack([aMat2,row_sum[:,np.newaxis]])
aMat2

array([[  66,   92,   98,   17,   83,   57,   86,   97,   96,   47,  739],
       [  73,   32,   46,   96,   25,   83,  215,   36,   96,   80,  782],
       [  68,   49,   55,   67,    2,   84,   39,   66,   84,   47,  561],
       [  61,  219,    7,   99,   92,   52,   97,   85,   94,   27,  833],
       [  34,   97,   76,   40,    3,   69,   64,   75,   34,   58,  550],
       [  10,   22,   77,   18,   15,   27,   30,   52,   70,   26,  347],
       [ 312,  511,  359,  337,  220,  372,  531,  411,  474,  285, 3812]])

In [398]:
# Q2
np.random.seed(123)
MAT = np.random.exponential(scale=1/5, size=(10, 7))
MAT= np.around(MAT, decimals=3 )

In [399]:
# 2-1
Q1 = np.percentile(MAT, 25)
Q3 = np.percentile(MAT, 75)

n1 = Q1-1.5*(Q3-Q1)
n2 = Q3+1.5*(Q3-Q1) 

MAT[(MAT<n1) | (MAT>n2)]

array([0.79 , 0.577, 0.848])

In [400]:
# 2-2
Transformed = np.abs(MAT - np.mean(MAT))
closest = np.min(Transformed)
closest
row, col = np.where(Transformed == closest)
print(row, col, MAT[[row, col]])

[7] [3] [0.185]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [401]:
# 2-3
MAT[np.argsort(MAT[:,1])]

array([[0.19 , 0.026, 0.35 , 0.185, 0.158, 0.084, 0.073],
       [0.238, 0.067, 0.051, 0.16 , 0.254, 0.11 , 0.79 ],
       [0.076, 0.107, 0.402, 0.058, 0.132, 0.848, 0.147],
       [0.075, 0.111, 0.448, 0.577, 0.139, 0.196, 0.025],
       [0.231, 0.131, 0.1  , 0.084, 0.261, 0.115, 0.012],
       [0.07 , 0.199, 0.019, 0.114, 0.113, 0.136, 0.111],
       [0.108, 0.229, 0.417, 0.143, 0.221, 0.176, 0.196],
       [0.379, 0.258, 0.189, 0.256, 0.078, 0.09 , 0.052],
       [0.102, 0.268, 0.04 , 0.039, 0.152, 0.152, 0.201],
       [0.225, 0.369, 0.017, 0.289, 0.056, 0.043, 0.17 ]])

In [402]:
# 2-4
MAT[:, np.argsort(np.mean(MAT, 0))]

array([[0.254, 0.238, 0.067, 0.79 , 0.16 , 0.11 , 0.051],
       [0.261, 0.231, 0.131, 0.012, 0.084, 0.115, 0.1  ],
       [0.152, 0.102, 0.268, 0.201, 0.039, 0.152, 0.04 ],
       [0.078, 0.379, 0.258, 0.052, 0.256, 0.09 , 0.189],
       [0.113, 0.07 , 0.199, 0.111, 0.114, 0.136, 0.019],
       [0.139, 0.075, 0.111, 0.025, 0.577, 0.196, 0.448],
       [0.132, 0.076, 0.107, 0.147, 0.058, 0.848, 0.402],
       [0.158, 0.19 , 0.026, 0.073, 0.185, 0.084, 0.35 ],
       [0.221, 0.108, 0.229, 0.196, 0.143, 0.176, 0.417],
       [0.056, 0.225, 0.369, 0.17 , 0.289, 0.043, 0.017]])

In [403]:
# check
np.mean(MAT[:, np.argsort(np.mean(MAT, 0))], 0)

array([0.1564, 0.1694, 0.1765, 0.1777, 0.1905, 0.195 , 0.2033])

In [404]:
# 2-5 Better way?
MAT[[[0],[2]],[1,3,4]], MAT[[0,0,0,2,2,2],[1,3,4,1,3,4]]

(array([[0.067, 0.16 , 0.254],
        [0.268, 0.039, 0.152]]),
 array([0.067, 0.16 , 0.254, 0.268, 0.039, 0.152]))

In [405]:
# 2-6
MAT[(MAT<n1) | (MAT>n2)] = np.nan

In [413]:
# 2-7
MAT[np.any(np.isnan(MAT),1)]

array([[0.238, 0.067, 0.051, 0.16 , 0.254, 0.11 ,   nan],
       [0.075, 0.111, 0.448,   nan, 0.139, 0.196, 0.025],
       [0.076, 0.107, 0.402, 0.058, 0.132,   nan, 0.147]])

# Assignment 7

In [2]:
import pandas as pd
import numpy as np

In [190]:
#1
world = pd.read_csv("world_small.csv", index_col='country', dtype={"gdppcap08":np.float64, "polityIV":np.float64})
world.head(10)

region  gdppcap08  polityIV
country                                      
Albania       C&E Europe     7715.0      17.8
Algeria           Africa     8033.0      10.0
Angola            Africa     5899.0       8.0
Argentina     S. America    14333.0      18.0
Armenia       C&E Europe     6070.0      15.0
Australia   Asia-Pacific    35677.0      20.0
Austria        W. Europe    38152.0      20.0
Azerbaijan    C&E Europe     8765.0       3.0
Bahrain      Middle East    34605.0       3.0
Bangladesh  Asia-Pacific     1334.0      16.0

In [191]:
#2
btm10 = world['polityIV'].sort_values()
btm10 = btm10[btm10<=np.percentile(world['polityIV'], 10)]
btm10

country
Qatar           0.0
Saudi Arabia    0.0
Uzbekistan      1.0
Turkmenistan    1.0
Swaziland       1.0
Iraq            1.0
Oman            2.0
UAE             2.0
Bhutan          2.0
Laos            3.0
Kuwait          3.0
China           3.0
Belarus         3.0
Bahrain         3.0
Azerbaijan      3.0
Eritrea         3.0
Cuba            3.0
Vietnam         3.0
Libya           3.0
Name: polityIV, dtype: float64

In [192]:
#3
afr = pd.DataFrame(world.loc[world.region=='Africa','polityIV'])

In [193]:
#4
np.nonzero(world.region=='S. America')

(array([  3,  14,  16,  24,  26,  30,  32,  36,  38,  51,  54,  55,  56,
         65,  95, 102, 103, 138, 140], dtype=int64),)

In [194]:
#5
world[['gdppcap08','polityIV']]
world.loc[:,'gdppcap08':'polityIV']
world.iloc[:,1:3]

gdppcap08   polityIV
country                                       
Albania                      7715.0  17.800000
Algeria                      8033.0  10.000000
Angola                       5899.0   8.000000
Argentina                   14333.0  18.000000
Armenia                      6070.0  15.000000
Australia                   35677.0  20.000000
Austria                     38152.0  20.000000
Azerbaijan                   8765.0   3.000000
Bahrain                     34605.0   3.000000
Bangladesh                   1334.0  16.000000
Belarus                     12261.0   3.000000
Belgium                     34493.0  20.000000
Benin                        1468.0  16.200000
Bhutan                       4755.0   2.000000
Bolivia                      4278.0  18.200000
Botswana                    13392.0  19.000000
Brazil                      10296.0  18.000000
Bulgaria                    12393.0  19.000000
Burkina Faso                 1161.0  10.000000
Cambodia                     1905.0  12.000000
Cameroon                     2215.0   6.000000
Canada                      36444.0  20.000000
Central African Republic      736.0  10.200000
Chad                         1455.0   8.000000
Chile                       14465.0  19.200000
China                        5962.0   3.000000
Colombia                     8885.0  17.000000
Comoros                      1169.0  15.800000
Congo Brazzaville            3946.0   6.000000
Congo Kinshasa                321.0  15.000000
...                             ...        ...
Slovakia                    22081.0  19.000000
Slovenia                    27605.0  20.000000
Solomon Islands              2610.0  18.000000
South Africa                10109.0  19.000000
Spain                       31954.0  20.000000
Sri Lanka                    4560.0  15.333333
Sudan                        2153.0   4.000000
Swaziland                    4928.0   1.000000
Sweden                      37383.0  20.000000
Switzerland                 42536.0  20.000000
Taiwan                      30881.0  19.333333
Tajikistan                   1906.0   7.666667
Tanzania                     1263.0  11.000000
Thailand                     7703.0  19.000000
Togo                          829.0   8.000000
Tunisia                      7996.0   6.000000
Turkey                      13920.0  17.000000
Turkmenistan                 6641.0   1.000000
UAE                         38830.0   2.000000
Uganda                       1165.0   6.000000
Ukraine                      7271.0  16.000000
United Kingdom              35445.0  20.000000
United States               46716.0  20.000000
Uruguay                     12734.0  20.000000
Uzbekistan                   2656.0   1.000000
Venezuela                   12804.0  16.000000
Vietnam                      2785.0   3.000000
Yemen                        2400.0   8.000000
Zambia                       1356.0  15.000000
Zimbabwe                      188.0   6.000000

[145 rows x 2 columns]

In [195]:
#6
world.loc[world.polityIV >= 20,'polityIV'] = np.nan
world

region  gdppcap08   polityIV
country                                                     
Albania                     C&E Europe     7715.0  17.800000
Algeria                         Africa     8033.0  10.000000
Angola                          Africa     5899.0   8.000000
Argentina                   S. America    14333.0  18.000000
Armenia                     C&E Europe     6070.0  15.000000
Australia                 Asia-Pacific    35677.0        NaN
Austria                      W. Europe    38152.0        NaN
Azerbaijan                  C&E Europe     8765.0   3.000000
Bahrain                    Middle East    34605.0   3.000000
Bangladesh                Asia-Pacific     1334.0  16.000000
Belarus                     C&E Europe    12261.0   3.000000
Belgium                      W. Europe    34493.0        NaN
Benin                           Africa     1468.0  16.200000
Bhutan                    Asia-Pacific     4755.0   2.000000
Bolivia                     S. America     4278.0  18.200000
Botswana                        Africa    13392.0  19.000000
Brazil                      S. America    10296.0  18.000000
Bulgaria                    C&E Europe    12393.0  19.000000
Burkina Faso                    Africa     1161.0  10.000000
Cambodia                  Asia-Pacific     1905.0  12.000000
Cameroon                        Africa     2215.0   6.000000
Canada                      N. America    36444.0        NaN
Central African Republic        Africa      736.0  10.200000
Chad                            Africa     1455.0   8.000000
Chile                       S. America    14465.0  19.200000
China                     Asia-Pacific     5962.0   3.000000
Colombia                    S. America     8885.0  17.000000
Comoros                         Africa     1169.0  15.800000
Congo Brazzaville               Africa     3946.0   6.000000
Congo Kinshasa                  Africa      321.0  15.000000
...                                ...        ...        ...
Slovakia                    C&E Europe    22081.0  19.000000
Slovenia                    C&E Europe    27605.0        NaN
Solomon Islands           Asia-Pacific     2610.0  18.000000
South Africa                    Africa    10109.0  19.000000
Spain                        W. Europe    31954.0        NaN
Sri Lanka                 Asia-Pacific     4560.0  15.333333
Sudan                           Africa     2153.0   4.000000
Swaziland                       Africa     4928.0   1.000000
Sweden                     Scandinavia    37383.0        NaN
Switzerland                  W. Europe    42536.0        NaN
Taiwan                    Asia-Pacific    30881.0  19.333333
Tajikistan                  C&E Europe     1906.0   7.666667
Tanzania                        Africa     1263.0  11.000000
Thailand                  Asia-Pacific     7703.0  19.000000
Togo                            Africa      829.0   8.000000
Tunisia                    Middle East     7996.0   6.000000
Turkey                     Middle East    13920.0  17.000000
Turkmenistan                C&E Europe     6641.0   1.000000
UAE                        Middle East    38830.0   2.000000
Uganda                          Africa     1165.0   6.000000
Ukraine                     C&E Europe     7271.0  16.000000
United Kingdom               W. Europe    35445.0        NaN
United States               N. America    46716.0        NaN
Uruguay                     S. America    12734.0        NaN
Uzbekistan                  C&E Europe     2656.0   1.000000
Venezuela                   S. America    12804.0  16.000000
Vietnam                   Asia-Pacific     2785.0   3.000000
Yemen                      Middle East     2400.0   8.000000
Zambia                          Africa     1356.0  15.000000
Zimbabwe                        Africa      188.0   6.000000

[145 rows x 3 columns]

# Assignment 8

In [196]:
#1
afr['population'] = np.random.randint(1000, 5000, len(afr))
afr

polityIV  population
country                                        
Algeria                   10.000000        1736
Angola                     8.000000        2696
Benin                     16.200000        1132
Botswana                  19.000000        4333
Burkina Faso              10.000000        2859
Cameroon                   6.000000        4349
Central African Republic  10.200000        1347
Chad                       8.000000        4831
Comoros                   15.800000        1921
Congo Brazzaville          6.000000        4537
Congo Kinshasa            15.000000        3310
Djibouti                  12.000000        2133
Equatorial Guinea          5.000000        3651
Eritrea                    3.000000        2020
Gabon                      6.000000        4745
Gambia                     5.000000        4966
Ghana                     16.666667        4392
Guinea                     9.000000        4509
Guinea-Bissau             11.000000        1157
Kenya                     18.000000        4086
Lesotho                   18.000000        1377
Liberia                   10.000000        4322
Madagascar                17.000000        4365
Malawi                    15.000000        2105
Mali                      16.000000        4087
Mauritania                 4.000000        4200
Mauritius                 20.000000        3289
Mozambique                16.000000        2622
Namibia                   16.000000        4780
Niger                     15.333333        2875
Nigeria                   14.000000        2901
Rwanda                     6.666667        4061
Senegal                   18.000000        2427
Sierra Leone              15.000000        2721
South Africa              19.000000        3149
Sudan                      4.000000        1267
Swaziland                  1.000000        4709
Tanzania                  11.000000        2172
Togo                       8.000000        1009
Uganda                     6.000000        2026
Zambia                    15.000000        3200
Zimbabwe                   6.000000        4707

In [197]:
#2
world['gdp'] = afr['population']*world['gdppcap08']
world

region  gdppcap08   polityIV         gdp
country                                                                 
Albania                     C&E Europe     7715.0  17.800000         NaN
Algeria                         Africa     8033.0  10.000000  13945288.0
Angola                          Africa     5899.0   8.000000  15903704.0
Argentina                   S. America    14333.0  18.000000         NaN
Armenia                     C&E Europe     6070.0  15.000000         NaN
Australia                 Asia-Pacific    35677.0        NaN         NaN
Austria                      W. Europe    38152.0        NaN         NaN
Azerbaijan                  C&E Europe     8765.0   3.000000         NaN
Bahrain                    Middle East    34605.0   3.000000         NaN
Bangladesh                Asia-Pacific     1334.0  16.000000         NaN
Belarus                     C&E Europe    12261.0   3.000000         NaN
Belgium                      W. Europe    34493.0        NaN         NaN
Benin                           Africa     1468.0  16.200000   1661776.0
Bhutan                    Asia-Pacific     4755.0   2.000000         NaN
Bolivia                     S. America     4278.0  18.200000         NaN
Botswana                        Africa    13392.0  19.000000  58027536.0
Brazil                      S. America    10296.0  18.000000         NaN
Bulgaria                    C&E Europe    12393.0  19.000000         NaN
Burkina Faso                    Africa     1161.0  10.000000   3319299.0
Cambodia                  Asia-Pacific     1905.0  12.000000         NaN
Cameroon                        Africa     2215.0   6.000000   9633035.0
Canada                      N. America    36444.0        NaN         NaN
Central African Republic        Africa      736.0  10.200000    991392.0
Chad                            Africa     1455.0   8.000000   7029105.0
Chile                       S. America    14465.0  19.200000         NaN
China                     Asia-Pacific     5962.0   3.000000         NaN
Colombia                    S. America     8885.0  17.000000         NaN
Comoros                         Africa     1169.0  15.800000   2245649.0
Congo Brazzaville               Africa     3946.0   6.000000  17903002.0
Congo Kinshasa                  Africa      321.0  15.000000   1062510.0
...                                ...        ...        ...         ...
Slovakia                    C&E Europe    22081.0  19.000000         NaN
Slovenia                    C&E Europe    27605.0        NaN         NaN
Solomon Islands           Asia-Pacific     2610.0  18.000000         NaN
South Africa                    Africa    10109.0  19.000000  31833241.0
Spain                        W. Europe    31954.0        NaN         NaN
Sri Lanka                 Asia-Pacific     4560.0  15.333333         NaN
Sudan                           Africa     2153.0   4.000000   2727851.0
Swaziland                       Africa     4928.0   1.000000  23205952.0
Sweden                     Scandinavia    37383.0        NaN         NaN
Switzerland                  W. Europe    42536.0        NaN         NaN
Taiwan                    Asia-Pacific    30881.0  19.333333         NaN
Tajikistan                  C&E Europe     1906.0   7.666667         NaN
Tanzania                        Africa     1263.0  11.000000   2743236.0
Thailand                  Asia-Pacific     7703.0  19.000000         NaN
Togo                            Africa      829.0   8.000000    836461.0
Tunisia                    Middle East     7996.0   6.000000         NaN
Turkey                     Middle East    13920.0  17.000000         NaN
Turkmenistan                C&E Europe     6641.0   1.000000         NaN
UAE                        Middle East    38830.0   2.000000         NaN
Uganda                          Africa     1165.0   6.000000   2360290.0
Ukraine                     C&E Europe     7271.0  16.000000         NaN
United Kingdom               W. Europe    35445.0        NaN         NaN
United States    

In [198]:
#3
world['gdp_log'] = np.log(world['gdp'])
world

region  gdppcap08   polityIV         gdp  \
country                                                                    
Albania                     C&E Europe     7715.0  17.800000         NaN   
Algeria                         Africa     8033.0  10.000000  13945288.0   
Angola                          Africa     5899.0   8.000000  15903704.0   
Argentina                   S. America    14333.0  18.000000         NaN   
Armenia                     C&E Europe     6070.0  15.000000         NaN   
Australia                 Asia-Pacific    35677.0        NaN         NaN   
Austria                      W. Europe    38152.0        NaN         NaN   
Azerbaijan                  C&E Europe     8765.0   3.000000         NaN   
Bahrain                    Middle East    34605.0   3.000000         NaN   
Bangladesh                Asia-Pacific     1334.0  16.000000         NaN   
Belarus                     C&E Europe    12261.0   3.000000         NaN   
Belgium                      W. Europe    34493.0        NaN         NaN   
Benin                           Africa     1468.0  16.200000   1661776.0   
Bhutan                    Asia-Pacific     4755.0   2.000000         NaN   
Bolivia                     S. America     4278.0  18.200000         NaN   
Botswana                        Africa    13392.0  19.000000  58027536.0   
Brazil                      S. America    10296.0  18.000000         NaN   
Bulgaria                    C&E Europe    12393.0  19.000000         NaN   
Burkina Faso                    Africa     1161.0  10.000000   3319299.0   
Cambodia                  Asia-Pacific     1905.0  12.000000         NaN   
Cameroon                        Africa     2215.0   6.000000   9633035.0   
Canada                      N. America    36444.0        NaN         NaN   
Central African Republic        Africa      736.0  10.200000    991392.0   
Chad                            Africa     1455.0   8.000000   7029105.0   
Chile                       S. America    14465.0  19.200000         NaN   
China                     Asia-Pacific     5962.0   3.000000         NaN   
Colombia                    S. America     8885.0  17.000000         NaN   
Comoros                         Africa     1169.0  15.800000   2245649.0   
Congo Brazzaville               Africa     3946.0   6.000000  17903002.0   
Congo Kinshasa                  Africa      321.0  15.000000   1062510.0   
...                                ...        ...        ...         ...   
Slovakia                    C&E Europe    22081.0  19.000000         NaN   
Slovenia                    C&E Europe    27605.0        NaN         NaN   
Solomon Islands           Asia-Pacific     2610.0  18.000000         NaN   
South Africa                    Africa    10109.0  19.000000  31833241.0   
Spain                        W. Europe    31954.0        NaN         NaN   
Sri Lanka                 Asia-Pacific     4560.0  15.333333         NaN   
Sudan                           Africa     2153.0   4.000000   2727851.0   
Swaziland                       Africa     4928.0   1.000000  23205952.0   
Sweden                     Scandinavia    37383.0        NaN         NaN   
Switzerland                  W. Europe    42536.0        NaN         NaN   
Taiwan                    Asia-Pacific    30881.0  19.333333         NaN   
Tajikistan                  C&E Europe     1906.0   7.666667         NaN   
Tanzania                        Africa     1263.0  11.000000   2743236.0   
Thailand                  Asia-Pacific     7703.0  19.000000         NaN   
Togo                            Africa      829.0   8.000000    836461.0   
Tunisia                    Middle East     7996.0   6.000000         NaN   
Turkey                     Middle East    13920.0  17.000000         NaN   
Turkmenistan                C&E Europe     6641.0   1.000000         NaN   
UAE                        Middle East    38830.0   2.000000         NaN   
Uganda                          Africa     1165.0   6.000000   2360290.0   
Ukra

In [199]:
#4
world_num = world[["gdppcap08", 'polityIV']]
world_num = (world_num - world_num.mean()) / world_num.std()
world_num

gdppcap08  polityIV
country                                      
Albania                   -0.374056  0.976214
Algeria                   -0.352573 -0.254945
Angola                    -0.496737 -0.570627
Argentina                  0.073028  1.007782
Armenia                   -0.485185  0.534259
Australia                  1.514939       NaN
Austria                    1.682139       NaN
Azerbaijan                -0.303122 -1.359832
Bahrain                    1.442519 -1.359832
Bangladesh                -0.805129  0.692100
Belarus                   -0.066947 -1.359832
Belgium                    1.434953       NaN
Benin                     -0.796077  0.723668
Bhutan                    -0.574021 -1.517673
Bolivia                   -0.606245  1.039350
Botswana                   0.009458  1.165623
Brazil                    -0.199694  1.007782
Bulgaria                  -0.058030  1.165623
Burkina Faso              -0.816817 -0.254945
Cambodia                  -0.766555  0.060736
Cameroon                  -0.745613 -0.886309
Canada                     1.566754       NaN
Central African Republic  -0.845528 -0.223377
Chad                      -0.796955 -0.570627
Chile                      0.081946  1.197191
China                     -0.492481 -1.359832
Colombia                  -0.295016  0.849941
Comoros                   -0.816276  0.660532
Congo Brazzaville         -0.628674 -0.886309
Congo Kinshasa            -0.873563  0.534259
...                             ...       ...
Slovakia                   0.596450  1.165623
Slovenia                   0.969629       NaN
Solomon Islands           -0.718928  1.007782
South Africa              -0.212327  1.165623
Spain                      1.263429       NaN
Sri Lanka                 -0.587194  0.586873
Sudan                     -0.749801 -1.201991
Swaziland                 -0.562334 -1.675514
Sweden                     1.630189       NaN
Switzerland                1.978304       NaN
Taiwan                     1.190941  1.218237
Tajikistan                -0.766487 -0.623241
Tanzania                  -0.809926 -0.097104
Thailand                  -0.374867  1.165623
Togo                      -0.839245 -0.570627
Tunisia                   -0.355073 -0.886309
Turkey                     0.045128  0.849941
Turkmenistan              -0.446611 -1.675514
UAE                        1.727942 -1.517673
Uganda                    -0.816546 -0.886309
Ukraine                   -0.404051  0.692100
United Kingdom             1.499266       NaN
United States              2.260687       NaN
Uruguay                   -0.034993       NaN
Uzbekistan                -0.715821 -1.675514
Venezuela                 -0.030265  0.692100
Vietnam                   -0.707106 -1.359832
Yemen                     -0.733115 -0.570627
Zambia                    -0.803643  0.534259
Zimbabwe                  -0.882548 -0.886309

[145 rows x 2 columns]

In [206]:
#5
world['polity'] = np.where(world['polityIV']>10, 1, 0)
world

region  gdppcap08   polityIV         gdp  \
country                                                                    
Albania                     C&E Europe     7715.0  17.800000         NaN   
Algeria                         Africa     8033.0  10.000000  13945288.0   
Angola                          Africa     5899.0   8.000000  15903704.0   
Argentina                   S. America    14333.0  18.000000         NaN   
Armenia                     C&E Europe     6070.0  15.000000         NaN   
Australia                 Asia-Pacific    35677.0        NaN         NaN   
Austria                      W. Europe    38152.0        NaN         NaN   
Azerbaijan                  C&E Europe     8765.0   3.000000         NaN   
Bahrain                    Middle East    34605.0   3.000000         NaN   
Bangladesh                Asia-Pacific     1334.0  16.000000         NaN   
Belarus                     C&E Europe    12261.0   3.000000         NaN   
Belgium                      W. Europe    34493.0        NaN         NaN   
Benin                           Africa     1468.0  16.200000   1661776.0   
Bhutan                    Asia-Pacific     4755.0   2.000000         NaN   
Bolivia                     S. America     4278.0  18.200000         NaN   
Botswana                        Africa    13392.0  19.000000  58027536.0   
Brazil                      S. America    10296.0  18.000000         NaN   
Bulgaria                    C&E Europe    12393.0  19.000000         NaN   
Burkina Faso                    Africa     1161.0  10.000000   3319299.0   
Cambodia                  Asia-Pacific     1905.0  12.000000         NaN   
Cameroon                        Africa     2215.0   6.000000   9633035.0   
Canada                      N. America    36444.0        NaN         NaN   
Central African Republic        Africa      736.0  10.200000    991392.0   
Chad                            Africa     1455.0   8.000000   7029105.0   
Chile                       S. America    14465.0  19.200000         NaN   
China                     Asia-Pacific     5962.0   3.000000         NaN   
Colombia                    S. America     8885.0  17.000000         NaN   
Comoros                         Africa     1169.0  15.800000   2245649.0   
Congo Brazzaville               Africa     3946.0   6.000000  17903002.0   
Congo Kinshasa                  Africa      321.0  15.000000   1062510.0   
...                                ...        ...        ...         ...   
Slovakia                    C&E Europe    22081.0  19.000000         NaN   
Slovenia                    C&E Europe    27605.0        NaN         NaN   
Solomon Islands           Asia-Pacific     2610.0  18.000000         NaN   
South Africa                    Africa    10109.0  19.000000  31833241.0   
Spain                        W. Europe    31954.0        NaN         NaN   
Sri Lanka                 Asia-Pacific     4560.0  15.333333         NaN   
Sudan                           Africa     2153.0   4.000000   2727851.0   
Swaziland                       Africa     4928.0   1.000000  23205952.0   
Sweden                     Scandinavia    37383.0        NaN         NaN   
Switzerland                  W. Europe    42536.0        NaN         NaN   
Taiwan                    Asia-Pacific    30881.0  19.333333         NaN   
Tajikistan                  C&E Europe     1906.0   7.666667         NaN   
Tanzania                        Africa     1263.0  11.000000   2743236.0   
Thailand                  Asia-Pacific     7703.0  19.000000         NaN   
Togo                            Africa      829.0   8.000000    836461.0   
Tunisia                    Middle East     7996.0   6.000000         NaN   
Turkey                     Middle East    13920.0  17.000000         NaN   
Turkmenistan                C&E Europe     6641.0   1.000000         NaN   
UAE                        Middle East    38830.0   2.000000         NaN   
Uganda                          Africa     1165.0   6.000000   2360290.0   
Ukra

In [209]:
#6
world.sort_values(by=['region', 'gdppcap08'], inplace=True)
world

region  gdppcap08   polityIV        gdp  \
country                                                                  
Zimbabwe                       Africa      188.0   6.000000   884916.0   
Congo Kinshasa                 Africa      321.0  15.000000  1062510.0   
Liberia                        Africa      388.0  10.000000  1676936.0   
Guinea-Bissau                  Africa      538.0  11.000000   622466.0   
Eritrea                        Africa      632.0   3.000000  1276640.0   
Niger                          Africa      684.0  15.333333  1966500.0   
Central African Republic       Africa      736.0  10.200000   991392.0   
Sierra Leone                   Africa      766.0  15.000000  2084286.0   
Togo                           Africa      829.0   8.000000   836461.0   
Malawi                         Africa      837.0  15.000000  1761885.0   
Mozambique                     Africa      855.0  16.000000  2241810.0   
Rwanda                         Africa     1022.0   6.666667  4150342.0   
Madagascar                     Africa     1049.0  17.000000  4578885.0   
Mali                           Africa     1128.0  16.000000  4610136.0   
Burkina Faso                   Africa     1161.0  10.000000  3319299.0   
Uganda                         Africa     1165.0   6.000000  2360290.0   
Comoros                        Africa     1169.0  15.800000  2245649.0   
Guinea                         Africa     1204.0   9.000000  5428836.0   
Tanzania                       Africa     1263.0  11.000000  2743236.0   
Zambia                         Africa     1356.0  15.000000  4339200.0   
Gambia                         Africa     1363.0   5.000000  6768658.0   
Ghana                          Africa     1452.0  16.666667  6377184.0   
Chad                           Africa     1455.0   8.000000  7029105.0   
Benin                          Africa     1468.0  16.200000  1661776.0   
Lesotho                        Africa     1588.0  18.000000  2186676.0   
Kenya                          Africa     1590.0  18.000000  6496740.0   
Senegal                        Africa     1772.0  18.000000  4300644.0   
Mauritania                     Africa     2052.0   4.000000  8618400.0   
Nigeria                        Africa     2082.0  14.000000  6039882.0   
Djibouti                       Africa     2140.0  12.000000  4564620.0   
...                               ...        ...        ...        ...   
Paraguay                   S. America     4709.0  17.666667        NaN   
Guatemala                  S. America     4760.0  18.000000        NaN   
El Salvador                S. America     6794.0  17.000000        NaN   
Jamaica                    S. America     7705.0  19.000000        NaN   
Ecuador                    S. America     8009.0  16.200000        NaN   
Peru                       S. America     8507.0  19.000000        NaN   
Colombia                   S. America     8885.0  17.000000        NaN   
Cuba                       S. America     9500.0   3.000000        NaN   
Brazil                     S. America    10296.0  18.000000        NaN   
Costa Rica                 S. America    11241.0        NaN        NaN   
Uruguay                    S. America    12734.0        NaN        NaN   
Venezuela                  S. America    12804.0  16.000000        NaN   
Argentina                  S. America    14333.0  18.000000        NaN   
Chile                      S. America    14465.0  19.200000        NaN   
Finland                   Scandinavia    35427.0        NaN        NaN   
Denmark                   Scandinavia    36607.0        NaN        NaN   
Sweden                    Scandinavia    37383.0        NaN        NaN   
Norway                    Scandinavia    58138.0        NaN        NaN   
Portugal                    W. Europe    23074.0        NaN        NaN   
Greece                      W. Europe    29361.0        NaN        NaN   
Italy                       W. Europe    30756.0        NaN        NaN   
Spain                       W. Euro

In [211]:
#7
world.sample(15, replace=False)

region  gdppcap08   polityIV         gdp    gdp_log  \
country                                                                      
Bulgaria           C&E Europe    12393.0  19.000000         NaN        NaN   
Taiwan           Asia-Pacific    30881.0  19.333333         NaN        NaN   
Honduras           S. America     3965.0  17.000000         NaN        NaN   
Nepal            Asia-Pacific     1112.0   4.000000         NaN        NaN   
Israel            Middle East    27548.0        NaN         NaN        NaN   
Guatemala          S. America     4760.0  18.000000         NaN        NaN   
Kuwait            Middle East    39914.0   3.000000         NaN        NaN   
Solomon Islands  Asia-Pacific     2610.0  18.000000         NaN        NaN   
Ghana                  Africa     1452.0  16.666667   6377184.0  15.668237   
Gambia                 Africa     1363.0   5.000000   6768658.0  15.727813   
New Zealand      Asia-Pacific    27029.0        NaN         NaN        NaN   
Botswana               Africa    13392.0  19.000000  58027536.0  17.876428   
United States      N. America    46716.0        NaN         NaN        NaN   
Bhutan           Asia-Pacific     4755.0   2.000000         NaN        NaN   
Finland           Scandinavia    35427.0        NaN         NaN        NaN   

                 polity  
country                  
Bulgaria              1  
Taiwan                1  
Honduras              1  
Nepal                 0  
Israel                0  
Guatemala             1  
Kuwait                0  
Solomon Islands       1  
Ghana                 1  
Gambia                0  
New Zealand           0  
Botswana              1  
United States         0  
Bhutan                0  
Finland               0

In [249]:
#2-1
autodata = pd.read_csv('automobile_data.csv')
#2-2
autodata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
index               61 non-null int64
company             61 non-null object
body-style          61 non-null object
wheel-base          61 non-null object
length              61 non-null float64
engine-type         61 non-null object
num-of-cylinders    61 non-null object
horsepower          61 non-null object
average-mileage     61 non-null int64
price               58 non-null float64
dtypes: float64(2), int64(2), object(6)
memory usage: 4.8+ KB


In [252]:
#2-3
autodata.head()

index      company   body-style wheel-base  length engine-type  \
0      0  alfa-romero  convertible       88.6   168.8        dohc   
1      1  alfa-romero  convertible       88.6   168.8        dohc   
2      2  alfa-romero    hatchback       94.5   171.2        ohcv   
3      3         audi        sedan       99.8   176.6         ohc   
4      4         audi        sedan       99.4   176.6         ohc   

  num-of-cylinders horsepower  average-mileage    price  
0             four        111               21  13495.0  
1             four        111               21  16500.0  
2              six        154               19  16500.0  
3             four        102               24  13950.0  
4             five        115               18  17450.0

In [255]:
# 2-4
autodata[autodata == "?"] = np.nan
autodata.head()

index      company   body-style wheel-base  length engine-type  \
0      0  alfa-romero  convertible       88.6   168.8        dohc   
1      1  alfa-romero  convertible       88.6   168.8        dohc   
2      2  alfa-romero    hatchback       94.5   171.2        ohcv   
3      3         audi        sedan       99.8   176.6         ohc   
4      4         audi        sedan       99.4   176.6         ohc   

  num-of-cylinders horsepower  average-mileage    price  
0             four        111               21  13495.0  
1             four        111               21  16500.0  
2              six        154               19  16500.0  
3             four        102               24  13950.0  
4             five        115               18  17450.0

In [259]:
# 2-5
autodata[['wheel-base', 'horsepower']] = autodata[['wheel-base', 'horsepower']].astype(np.float64, inplace=True)
autodata

index        company   body-style  wheel-base  length engine-type  \
0       0    alfa-romero  convertible        88.6   168.8        dohc   
1       1    alfa-romero  convertible        88.6   168.8        dohc   
2       2    alfa-romero    hatchback        94.5   171.2        ohcv   
3       3           audi        sedan        99.8   176.6         ohc   
4       4           audi        sedan        99.4   176.6         ohc   
5       5           audi        sedan        99.8   177.3         ohc   
6       6           audi        wagon       105.8   192.7         ohc   
7       9            bmw        sedan         NaN   176.8         ohc   
8      10            bmw        sedan       101.2   176.8         ohc   
9      11            bmw        sedan       101.2   176.8         ohc   
10     13            bmw        sedan       103.5   189.0         ohc   
11     14            bmw        sedan       103.5   193.8         ohc   
12     15            bmw        sedan       110.0   197.0         ohc   
13     16      chevrolet    hatchback        88.4   141.1         NaN   
14     17      chevrolet    hatchback        94.5   155.9         ohc   
15     18      chevrolet        sedan        94.5   158.8         ohc   
16     19          dodge    hatchback        93.7   157.3         ohc   
17     20          dodge    hatchback        93.7   157.3         ohc   
18     27          honda        wagon        96.5   157.1         ohc   
19     28          honda        sedan        96.5   175.4         ohc   
20     29          honda        sedan        96.5   169.1         ohc   
21     30          isuzu        sedan        94.3   170.7         ohc   
22     31          isuzu          NaN        94.5   155.9         ohc   
23     32          isuzu        sedan        94.5   155.9         ohc   
24     33         jaguar        sedan       113.0   199.6        dohc   
25     34         jaguar        sedan       113.0   199.6        dohc   
26     35         jaguar        sedan       102.0   191.7        ohcv   
27     36          mazda    hatchback        93.1   159.1         ohc   
28     37          mazda    hatchback        93.1   159.1         ohc   
29     38          mazda    hatchback        93.1   159.1         ohc   
..    ...            ...          ...         ...     ...         ...   
31     43          mazda        sedan       104.9   175.0         ohc   
32     44  mercedes-benz        sedan       110.0   190.9         ohc   
33     45  mercedes-benz        wagon       110.0   190.9         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
36     49     mitsubishi    hatchback        93.7   157.3         ohc   
37     50     mitsubishi    hatchback        93.7   157.3         ohc   
38     51     mitsubishi        sedan        96.3   172.4         ohc   
39     52     mitsubishi        sedan        96.3   172.4         ohc   
40     53         nissan        sedan        94.5   165.3         ohc   
41     54         nissan        sedan        94.5   165.3         ohc   
42     55         nissan        sedan        94.5   165.3         ohc   
43     56         nissan        wagon        94.5   170.2         ohc   
44     57         nissan        sedan       100.4   184.6        ohcv   
45     61        porsche      hardtop        89.5   168.9        ohcf   
46     62        porsche  convertible        89.5   168.9        ohcf   
47     63        porsche    hatchback        98.4   175.7       dohcv   
48     66         toyota    hatchback        95.7   158.7         ohc   
49     67         toyota    hatchback        95.7   158.7         ohc   
50     68         toyota    hatchback        95.7   158.7         ohc   
51     69         toyota        wagon        95.7   169.7         ohc   
52     70         toyota        wagon        95.7   169.7         ohc   
53     71         toyota        wagon        95.7   169.7     

In [256]:
# 2-6
autodata['price'].max()

45400.0

In [264]:
# 2-7
autodata[autodata['company'] == 'toyota']

index company body-style  wheel-base  length engine-type num-of-cylinders  \
48     66  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
53     71  toyota      wagon        95.7   169.7         ohc             four   
54     79  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48        62.0               35   5348.0  
49        62.0               31   6338.0  
50        62.0               31   6488.0  
51        62.0               31   6918.0  
52        62.0               27   7898.0  
53        62.0               27   8778.0  
54         NaN               19  15750.0

In [266]:
# 2-8
autodata['company'].value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
volkswagen       4
mitsubishi       4
mercedes-benz    4
audi             4
porsche          3
honda            3
chevrolet        3
alfa-romero      3
jaguar           3
isuzu            3
dodge            2
volvo            2
Name: company, dtype: int64

In [270]:
# 2-9
autodata.groupby('company').aggregate({'price': max})

price
company               
alfa-romero    16500.0
audi           18920.0
bmw            41315.0
chevrolet       6575.0
dodge           6377.0
honda          12945.0
isuzu           6785.0
jaguar         36000.0
mazda          18344.0
mercedes-benz  45400.0
mitsubishi      8189.0
nissan         13499.0
porsche        37028.0
toyota         15750.0
volkswagen      9995.0
volvo          13415.0

In [278]:
# 2-10
autodata.groupby('company').aggregate({'average-mileage': np.mean})

average-mileage
company                       
alfa-romero          20.333333
audi                 20.000000
bmw                  19.000000
chevrolet            41.000000
dodge                31.000000
honda                26.333333
isuzu                33.333333
jaguar               14.333333
mazda                28.000000
mercedes-benz        18.000000
mitsubishi           29.500000
nissan               31.400000
porsche              17.000000
toyota               28.714286
volkswagen           31.750000
volvo                23.000000

In [283]:
# 2-11 ??always skipna?
autodata.count(axis=0)

index               61
company             61
body-style          60
wheel-base          60
length              61
engine-type         60
num-of-cylinders    59
horsepower          60
average-mileage     61
price               58
dtype: int64

In [318]:
# 3-1
stdalc = pd.read_csv('student_alc.csv')
# 3-2
stdalc.columns[16]

'famsup'

In [319]:
# 3-3
stdalc.drop('address', axis=1, inplace=True)

In [320]:
# 3-4
stdalc['Mjob'] = stdalc['Mjob'].str.upper()
stdalc['Fjob'] = stdalc['Fjob'].str.upper()

In [321]:
stdalc['legal_drinker'] = np.where(stdalc['age']>18, True, False)
stdalc

school sex  age famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18     GT3       A     4     4   AT_HOME   TEACHER   
1       GP   F   17     GT3       T     1     1   AT_HOME     OTHER   
2       GP   F   15     LE3       T     1     1   AT_HOME     OTHER   
3       GP   F   15     GT3       T     4     2    HEALTH  SERVICES   
4       GP   F   16     GT3       T     3     3     OTHER     OTHER   
5       GP   M   16     LE3       T     4     3  SERVICES     OTHER   
6       GP   M   16     LE3       T     2     2     OTHER     OTHER   
7       GP   F   17     GT3       A     4     4     OTHER   TEACHER   
8       GP   M   15     LE3       A     3     2  SERVICES     OTHER   
9       GP   M   15     GT3       T     3     4     OTHER     OTHER   
10      GP   F   15     GT3       T     4     4   TEACHER    HEALTH   
11      GP   F   15     GT3       T     2     1  SERVICES     OTHER   
12      GP   M   15     LE3       T     4     4    HEALTH  SERVICES   
13      GP   M   15     GT3       T     4     3   TEACHER     OTHER   
14      GP   M   15     GT3       A     2     2     OTHER     OTHER   
15      GP   F   16     GT3       T     4     4    HEALTH     OTHER   
16      GP   F   16     GT3       T     4     4  SERVICES  SERVICES   
17      GP   F   16     GT3       T     3     3     OTHER     OTHER   
18      GP   M   17     GT3       T     3     2  SERVICES  SERVICES   
19      GP   M   16     LE3       T     4     3    HEALTH     OTHER   
20      GP   M   15     GT3       T     4     3   TEACHER     OTHER   
21      GP   M   15     GT3       T     4     4    HEALTH    HEALTH   
22      GP   M   16     LE3       T     4     2   TEACHER     OTHER   
23      GP   M   16     LE3       T     2     2     OTHER     OTHER   
24      GP   F   15     GT3       T     2     4  SERVICES    HEALTH   
25      GP   F   16     GT3       T     2     2  SERVICES  SERVICES   
26      GP   M   15     GT3       T     2     2     OTHER     OTHER   
27      GP   M   15     GT3       T     4     2    HEALTH  SERVICES   
28      GP   M   16     LE3       A     3     4  SERVICES     OTHER   
29      GP   M   16     GT3       T     4     4   TEACHER   TEACHER   
..     ...  ..  ...     ...     ...   ...   ...       ...       ...   
365     MS   M   18     GT3       T     1     3   AT_HOME     OTHER   
366     MS   M   18     LE3       T     4     4   TEACHER  SERVICES   
367     MS   F   17     GT3       T     1     1     OTHER  SERVICES   
368     MS   F   18     GT3       T     2     3   AT_HOME  SERVICES   
369     MS   F   18     GT3       T     4     4     OTHER   TEACHER   
370     MS   F   19     LE3       T     3     2  SERVICES  SERVICES   
371     MS   M   18     LE3       T     1     2   AT_HOME  SERVICES   
372     MS   F   17     GT3       T     2     2     OTHER   AT_HOME   
373     MS   F   17     GT3       T     1     2     OTHER     OTHER   
374     MS   F   18     LE3       T     4     4     OTHER     OTHER   
375     MS   F   18     GT3       T     1     1     OTHER     OTHER   
376     MS   F   20     GT3       T     4     2    HEALTH     OTHER   
377     MS   F   18     LE3       T     4     4   TEACHER  SERVICES   
378     MS   F   18     GT3       T     3     3     OTHER     OTHER   
379     MS   F   17     GT3       T     3     1   AT_HOME     OTHER   
380     MS   M   18     GT3       T     4     4   TEACHER   TEACHER   
381     MS   M   18     GT3       T     2     1     OTHER     OTHER   
382     MS   M   17     GT3       T     2     3     OTHER  SERVICES   
383     MS   M   19     GT3       T     1     1     OTHER  SERVICES   
384     MS   M   18     GT3       T     4     2     OTHER     OTHER   
385     MS   F   18     GT3       T     2     2   AT_HOME     OTHER   
386     MS   F   18     GT3       T     4     4   TEACHER   AT_HOME   
387     MS   F   19     GT3       T     2     3  SERVICES     OTHER   
388     MS   F   18     LE3       T     3     1   TEACHER  SERVICES   
389     MS   F   18     GT3 

In [3]:
# 4-1
users = pd.read_csv('users.csv')
users.head()

user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [4]:
#4-2
users.groupby('occupation')['age'].mean()
users.groupby('occupation').aggregate({'age': np.mean})

age
occupation              
administrator  38.746835
artist         31.392857
doctor         43.571429
educator       42.010526
engineer       36.388060
entertainment  29.222222
executive      38.718750
healthcare     41.562500
homemaker      32.571429
lawyer         36.750000
librarian      40.000000
marketing      37.615385
none           26.555556
other          34.523810
programmer     33.121212
retired        63.071429
salesman       35.666667
scientist      35.548387
student        22.081633
technician     33.148148
writer         36.311111

In [68]:
#4-3 should the solution be this hard?
males = users[users['gender'] == 'M']
ratio = males.groupby('occupation').count() / users.groupby('occupation').count()
ratio['gender']

occupation
administrator    0.544304
artist           0.535714
doctor           1.000000
educator         0.726316
engineer         0.970149
entertainment    0.888889
executive        0.906250
healthcare       0.312500
homemaker        0.142857
lawyer           0.833333
librarian        0.431373
marketing        0.615385
none             0.555556
other            0.657143
programmer       0.909091
retired          0.928571
salesman         0.750000
scientist        0.903226
student          0.693878
technician       0.962963
writer           0.577778
Name: gender, dtype: float64

In [88]:
# 4-4

users.groupby(['occupation', 'gender']).aggregate({'age': [max, np.mean, min]})

age               
                     max       mean min
occupation    gender                   
administrator F       62  40.638889  22
              M       70  37.162791  21
artist        F       48  30.307692  19
              M       45  32.333333  20
doctor        M       64  43.571429  28
educator      F       51  39.115385  23
              M       63  43.101449  25
engineer      F       36  29.500000  23
              M       70  36.600000  22
entertainment F       38  31.000000  24
              M       50  29.000000  15
executive     F       49  44.000000  39
              M       69  38.172414  22
healthcare    F       53  39.818182  22
              M       62  45.400000  28
homemaker     F       50  34.166667  20
              M       23  23.000000  23
lawyer        F       51  39.500000  28
              M       53  36.200000  21
librarian     F       59  40.000000  26
              M       69  40.000000  23
marketing     F       50  37.200000  24
              M       55  37.875000  24
none          F       55  36.500000  26
              M       33  18.600000  11
other         F       55  35.472222  18
              M       64  34.028986  13
programmer    F       38  32.166667  26
              M       63  33.216667  20
retired       F       70  70.000000  70
              M       73  62.538462  51
salesman      F       33  27.000000  18
              M       66  38.555556  21
scientist     F       31  28.333333  26
              M       55  36.321429  23
student       F       38  20.750000  13
              M       42  22.669118   7
technician    F       38  38.000000  38
              M       55  32.961538  21
writer        F       56  37.631579  18
              M       60  35.346154  21