In [4]:
import numpy as np

In [7]:
# 4
Z = (np.random.rand(5)-0)/(1)
Z

array([0.17708049, 0.70592764, 0.21065995, 0.45682909, 0.77454979])

In [12]:
# 5
Z = np.random.uniform(0,10,10)
Z = np.array(Z, dtype='int32')
Z

array([1, 8, 1, 8, 7, 0, 5, 2, 5, 8])

In [18]:
# 6
x = np.arange(1,101,1) * -1
x

array([  -1,   -2,   -3,   -4,   -5,   -6,   -7,   -8,   -9,  -10,  -11,
        -12,  -13,  -14,  -15,  -16,  -17,  -18,  -19,  -20,  -21,  -22,
        -23,  -24,  -25,  -26,  -27,  -28,  -29,  -30,  -31,  -32,  -33,
        -34,  -35,  -36,  -37,  -38,  -39,  -40,  -41,  -42,  -43,  -44,
        -45,  -46,  -47,  -48,  -49,  -50,  -51,  -52,  -53,  -54,  -55,
        -56,  -57,  -58,  -59,  -60,  -61,  -62,  -63,  -64,  -65,  -66,
        -67,  -68,  -69,  -70,  -71,  -72,  -73,  -74,  -75,  -76,  -77,
        -78,  -79,  -80,  -81,  -82,  -83,  -84,  -85,  -86,  -87,  -88,
        -89,  -90,  -91,  -92,  -93,  -94,  -95,  -96,  -97,  -98,  -99,
       -100])

In [20]:
# 7
degrees_c = np.arange(20,31)
degrees_f = degrees_c*9/5 + 32
degrees_f

array([68. , 69.8, 71.6, 73.4, 75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. ])

In [119]:
np.random.seed(123)
mat = np.random.randn(6,4); mat

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904]])

In [120]:
# 8
y = np.exp(mat[::,0])
y = y[:, np.newaxis]
y

array([[0.33768877],
       [0.56068263],
       [3.54641154],
       [4.44326571],
       [9.07869158],
       [2.09042747]])

In [121]:
mat = np.hstack((mat, y))
mat

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471,  0.33768877],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263,  0.56068263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897,  3.54641154],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128,  4.44326571],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ,  9.07869158],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904,  2.09042747]])

In [141]:
# 9 
print(mat[::,::2] + 1, mat[::,1::2] - 1, sep="\n")

[[-0.0856306   1.2829785   1.33768877]
 [ 0.42139975 -1.42667924  1.56068263]
 [ 2.26593626  0.32111385  4.54641154]
 [ 2.49138963  0.55601804  5.44326571]
 [ 3.20593008  2.0040539  10.07869158]
 [ 1.73736858  0.06416613  3.09042747]]
[[-0.00265455 -2.50629471]
 [ 0.65143654 -1.42891263]
 [-1.8667404  -1.09470897]
 [-1.638902   -1.43435128]
 [ 1.18678609 -0.6138136 ]
 [ 0.49073203  0.17582904]]


In [142]:
# 10
print(mat[:3]/10, mat[3:]*10, sep="\n")


[[-0.10856306  0.09973454  0.02829785 -0.15062947  0.03376888]
 [-0.05786003  0.16514365 -0.24266792 -0.04289126  0.05606826]
 [ 0.12659363 -0.08667404 -0.06788862 -0.0094709   0.35464115]]
[[14.91389626 -6.38901997 -4.4398196  -4.34351276 44.43265709]
 [22.05930083 21.86786089 10.04053898  3.86186399 90.78691576]
 [ 7.37368576 14.90732028 -9.35833868 11.75829045 20.90427469]]


In [143]:
# 11
print(np.median(mat, 0), np.percentile(mat, [0, 70, 100], 0), sep="\n")

[ 1.00165242  1.24403874 -0.56143406 -0.2618108   2.81841951]
[[-1.0856306  -0.8667404  -2.42667924 -1.50629471  0.33768877]
 [ 1.37866294  1.57108428 -0.08050173  0.14573872  3.99483862]
 [ 2.20593008  2.18678609  1.0040539   1.17582904  9.07869158]]


In [150]:
# 12
x = np.sort(mat[3,::])
x = x[::-1]
print(x)

[ 4.44326571  1.49138963 -0.43435128 -0.44398196 -0.638902  ]


In [158]:
# 13
greater_3 = mat > 3
x = np.sum(greater_3, 1)
x[:, np.newaxis]

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0]])

In [164]:
# 14
where = mat > np.mean(mat, 0)
np.nonzero(where)

(array([0, 0, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5], dtype=int64),
 array([1, 2, 1, 0, 3, 4, 0, 2, 4, 0, 1, 2, 3, 4, 0, 1, 3], dtype=int64))

In [169]:
# 15
np.random.seed(123)
M = np.random.randint(1,50,(3,3))
M@np.transpose(M)

array([[2966, 2249, 1716],
       [2249, 3070, 2791],
       [1716, 2791, 2778]])

In [172]:
np.linalg.det(M)

25347.999999999975

In [173]:
np.linalg.inv(M)

array([[ 0.00485245,  0.04647309, -0.04248856],
       [-0.01755563,  0.0188575 ,  0.00737731],
       [ 0.02860186, -0.07566672,  0.06663248]])