In [1]:
import numpy as np

In [89]:
#(1)	Generate a 2 dimensional array with shape (2, 5) by randomly extracting 10 integers between 10 and 30 inclusive.
np.random.randint(10,31, (2,5))

array([[20, 11, 11, 29, 12],
       [28, 11, 20, 13, 13]])

In [2]:
np.random.randint(10,31,(2,5))

array([[18, 12, 22, 22, 26],
       [14, 17, 15, 16, 13]])

In [104]:
#(2)	Extract 9 random numbers from the standard normal distribution and use them to create an array with shape (3, 3, 1).
np.random.randn(3,3,1)

array([[[ 0.90528104],
        [-1.68217487],
        [ 0.31997341]],

       [[-0.30444759],
        [ 0.05024274],
        [ 0.08942251]],

       [[ 0.60475687],
        [-0.97328202],
        [ 1.27965574]]])

In [4]:
np.random.randn(3,3,1)

array([[[-0.49924036],
        [-0.73524104],
        [-0.54081265]],

       [[-0.29437922],
        [ 0.46291018],
        [-1.2780111 ]],

       [[ 0.63330072],
        [ 0.5515881 ],
        [ 0.08709351]]])

In [9]:
#(3)	Randomly extract 6 real numbers between 0 and 1 and use them to create a one-dimensional array.
np.random.rand(6)

array([[0.70942531, 0.84032656, 0.51442317, 0.80732336, 0.88153197,
        0.86820615]])

In [101]:
#(4)	 주의 Create a two-dimensional diagonal matrix with the diagonal elements 1, 1.5, 2, 2.5, ... , 4.
np.diag(np.arange(1,4.1,0.5))

array([[1. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1.5, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 2. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 2.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 3. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 3.5, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 4. ]])

In [19]:
Z = np.zeros((8,8), dtype=np.int64)
Z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [108]:
Z[1::2,::2] = 1
Z[0::2,1::2] = 1
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int64)

In [23]:
#3 	Create the 2-dimensional 6×5 ndarray as the picture below.
six_five = np.array([[0+10*x, 1+10*x, 2+10*x, 3+10*x, 4+10*x, 5+10*x] for x in range(6)])
six_five

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [110]:
#3 (1)	Write the code to select the values in orange box as a one-dimensional ndarray.
six_five[0,3:5]

array([3, 4])

In [118]:
#3 (2)	Write the code to select the values in cyan box as a two-dimensional ndarray with shape (2,2).
six_five[4:,4:]

array([[44, 45],
       [54, 55]])

In [ ]:
#3-3
six_five[::,2]

In [122]:
#3-4 주의
six_five[::,2].reshape(6,1)

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52]])

In [124]:
#3-5
six_five[::,2] = range(6)
six_five

array([[ 0,  1,  0,  3,  4,  5],
       [10, 11,  1, 13, 14, 15],
       [20, 21,  2, 23, 24, 25],
       [30, 31,  3, 33, 34, 35],
       [40, 41,  4, 43, 44, 45],
       [50, 51,  5, 53, 54, 55]])

In [127]:
#3-6
six_five[2::2, ::2]

array([[20,  2, 24],
       [40,  4, 44]])

In [140]:
#3-7 주의
six_five[2::2,::2] = np.arange(1,7).reshape(2,3)
six_five

array([[ 0,  1,  0,  3,  4,  5],
       [10, 11,  1, 13, 14, 15],
       [ 1, 21,  2, 23,  3, 25],
       [30, 31,  3, 33, 34, 35],
       [ 4, 41,  5, 43,  6, 45],
       [50, 51,  5, 53, 54, 55]])

In [45]:
# 4 주의
Z = np.random.rand(5)
(Z- np.min(Z)) / (np.max(Z) - np.min(Z))

array([0.52116208, 1.        , 0.35872021, 0.68729904, 0.        ])

In [49]:
# 5
Z = np.random.uniform(0,10,10)
Z // 1

array([5., 2., 9., 0., 4., 2., 1., 2., 2., 0.])

In [152]:
# 6
x = np.arange(1,101,1) 
x[1::2] *= -1
x

array([   1,   -2,    3,   -4,    5,   -6,    7,   -8,    9,  -10,   11,
        -12,   13,  -14,   15,  -16,   17,  -18,   19,  -20,   21,  -22,
         23,  -24,   25,  -26,   27,  -28,   29,  -30,   31,  -32,   33,
        -34,   35,  -36,   37,  -38,   39,  -40,   41,  -42,   43,  -44,
         45,  -46,   47,  -48,   49,  -50,   51,  -52,   53,  -54,   55,
        -56,   57,  -58,   59,  -60,   61,  -62,   63,  -64,   65,  -66,
         67,  -68,   69,  -70,   71,  -72,   73,  -74,   75,  -76,   77,
        -78,   79,  -80,   81,  -82,   83,  -84,   85,  -86,   87,  -88,
         89,  -90,   91,  -92,   93,  -94,   95,  -96,   97,  -98,   99,
       -100])

In [20]:
# 7
degrees_c = np.arange(20,31)
degrees_f = degrees_c*9/5 + 32
degrees_f

array([68. , 69.8, 71.6, 73.4, 75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. ])

In [55]:
np.random.seed(123)
mat = np.random.randn(6,4); mat

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904]])

In [174]:
# 8 주의
y = np.exp(mat[::,0]).reshape(6,1)
y

array([[0.33768877],
       [0.56068263],
       [3.54641154],
       [4.44326571],
       [9.07869158],
       [2.09042747]])

In [175]:
mat = np.hstack((mat,y))
mat

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471,  0.33768877],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263,  0.56068263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897,  3.54641154],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128,  4.44326571],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ,  9.07869158],
       [ 0.73736858,  1.49073203, -0.93583387,  1.17582904,  2.09042747]])

In [176]:
# 9 
mat[::,::2] +=1
mat[::,1::2] += -1
mat += np.array([1,-1,1,-1,1])
mat

array([[ 0.9143694 , -1.00265455,  2.2829785 , -3.50629471,  2.33768877],
       [ 1.42139975, -0.34856346, -0.42667924, -2.42891263,  2.56068263],
       [ 3.26593626, -2.8667404 ,  1.32111385, -2.09470897,  5.54641154],
       [ 3.49138963, -2.638902  ,  1.55601804, -2.43435128,  6.44326571],
       [ 4.20593008,  0.18678609,  3.0040539 , -1.6138136 , 11.07869158],
       [ 2.73736858, -0.50926797,  1.06416613, -0.82417096,  4.09042747]])

In [66]:
# 10 주의
mat[0:3,::] *= 0.1
mat[3:,] *= 10
mat

array([[-1.08563060e-03,  9.97345447e-04,  2.82978498e-04,
        -1.50629471e-03],
       [-5.78600252e-04,  1.65143654e-03, -2.42667924e-03,
        -4.28912629e-04],
       [ 1.26593626e-03, -8.66740402e-04, -6.78886152e-04,
        -9.47089689e-05],
       [ 1.49138963e+02, -6.38901997e+01, -4.43981960e+01,
        -4.34351276e+01],
       [ 2.20593008e+02,  2.18678609e+02,  1.00405390e+02,
         3.86186399e+01],
       [ 7.37368576e+01,  1.49073203e+02, -9.35833868e+01,
         1.17582904e+02]])

In [67]:
# 11
np.percentile(mat, 70, axis=0)


array([ 1.11437910e+02,  7.45374271e+01, -1.97953827e-04,  1.93092726e+01])

In [68]:
# 12 주의
np.sort(mat[2])[::-1]


array([ 1.26593626e-03, -9.47089689e-05, -6.78886152e-04, -8.66740402e-04])

In [182]:
# 13
greater_3 = np.exp(mat) > 3
np.sum(greater_3, axis =1)

array([0, 0, 0, 3, 4, 3])

In [78]:
# 14
np.nonzero(mat > np.mean(mat, axis=0))

(array([0, 1, 2, 3, 4, 4, 4, 4, 5, 5], dtype=int64),
 array([2, 2, 2, 0, 0, 1, 2, 3, 1, 3], dtype=int64))

In [79]:
np.random.seed(123)
M = np.random.randint(1, 50, size=(3,3))
M

array([[46,  3, 29],
       [35, 39, 18],
       [20, 43, 23]])

In [77]:
np.nonzero(mat > np.mean(mat, 0))

(array([0, 1, 2, 3, 4, 4, 4, 4, 5, 5], dtype=int64),
 array([2, 2, 2, 0, 0, 1, 2, 3, 1, 3], dtype=int64))

In [80]:
#15
M @ M.T

array([[2966, 2249, 1716],
       [2249, 3070, 2791],
       [1716, 2791, 2778]])

In [81]:
#15
M @ M.T

array([[2966, 2249, 1716],
       [2249, 3070, 2791],
       [1716, 2791, 2778]])

In [82]:
np.linalg.det(M)

25347.999999999975

In [84]:
np.linalg.inv(M)

array([[ 0.00485245,  0.04647309, -0.04248856],
       [-0.01755563,  0.0188575 ,  0.00737731],
       [ 0.02860186, -0.07566672,  0.06663248]])